#!/bin/sh

#create swap
if [ -e /var/etc/.swapcreate.sh ]; then
	/usr/bin/showiframe /boot/bootlogo_swap.mvi
	/var/etc/.swapcreate.sh
	rm -f /var/etc/.swapcreate.sh
	/usr/bin/showiframe /boot/bootlogo.mvi
fi

[ -e /usr/script/mount.sh ] && /usr/script/mount.sh
[ -e /usr/bin/nemesisd ] && /usr/bin/nemesisd &

#Start tihrd-part at boot
list=`ls /var/etc/*_startup.sh`
for item in $list
	do
		${item} start
	done

#Start device
if [ `ls -al /dev/sda | grep disk -c` -ne "0" ]; then
	if [ -b /dev/sdc ]; then
		if [ -b /dev/sdd ]; then 
			mount /dev/sdc1 /media/usb || mount /dev/sdc /media/usb
		
	fi
else
	umount /media/hdd
	if [ -b /dev/sdc ]; then
		if [ -b /dev/sdd ]; then 
			mount /dev/sdc1 /media/usb || mount /dev/sdc /media/usb
	
	fi
fi

#Activate Swap
[ -e /media/usb/swapfile ] && swapon /media/usb/swapfile
[ -e /media/hdd/swapfile ] && swapon /media/hdd/swapfile

#Restore EPG
[ -e /media/hdd/epg.dat.save ] && cp /media/hdd/epg.dat.save /media/hdd/epg.dat
[ -e /media/usb/epg.dat.save ] && cp /media/usb/epg.dat.save /media/usb/epg.dat


